from setuptools import setup, find_packages

setup(
    name="nexuss-transformer",
    version="1.0.0",
    description="Nexuss Transformer Framework (NTF) - Blank Slate LLM Training with RLHF & EthioBBPE Support",
    author="nexuss0781",
    author_email="nexuss0781@gmail.com",
    url="https://github.com/nexuss0781/Nexuss-Transformer",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.56.2",
        "accelerate>=0.20.0",
        "peft>=0.19.0",
        "trl>=1.3.0",
        "datasets>=2.0.0",
        "tokenizers>=0.21,<0.22",
        "ethiobbpe>=1.0.1",
        "wandb>=0.15.0",
        "optuna>=3.0.0",
        "scipy>=1.10.0",
        "numpy>=1.24.0",
        "pyyaml>=6.0",
        "tqdm>=4.65.0",
    ],
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
